#?????
spring:
  application:
    name: gateway
  cloud:
    gateway:
      #      filter:
      #        strip-prefix:
      #          enabled: true
      routes: # ??????
        - id: content-api # ??id???????????
          # uri: http://127.0.0.1:5050 # ??????? http??????
          uri: lb://user-api # ??????? lb??????????????
          predicates: # ???????????????????????
            - Path=/user/** # ?????????????/content/???????
        #          filters:
        #            - StripPrefix=1

server:
  port: 3214